In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        # print(os.path.join(dirname, filename))
        ...
# /kaggle/input/cats-vs-dogs-classification
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [80]:
import cv2
import random
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
# !pip install opencv-python
# !pip install tensorflow

In [63]:
DATADIR = '/kaggle/input/dogs-vs-cats/dataset/train'
DATADIR2 = '/kaggle/input/dogs-vs-cats/dataset/test'
categories = ['cats',"dogs"]

In [14]:
img_size = 50
training_data = []
for category in categories:
    path = os.path.join(DATADIR,category)
    for img in os.listdir(path):
        class_num = categories.index(category)
        img_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
        new_array = cv2.resize(img_array,(img_size,img_size))
        training_data.append([new_array,class_num])


In [81]:
# testing_data = []
for category in categories:
    path = os.path.join(DATADIR2,category)
    for img in os.listdir(path):
        class_num = categories.index(category)
        img_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
        new_array = cv2.resize(img_array,(img_size,img_size))
        training_data.append([new_array,class_num])


In [82]:
random.shuffle(training_data)

In [154]:
X = []
y = []
for feature,label in training_data:
    X.append(feature)
    y.append(label)

X =  np.array(X).reshape(-1,img_size,img_size)

In [159]:
print(X_train[0])

[[ 69  73  68 ...  99  90  93]
 [ 69  66  63 ... 101  94  97]
 [ 72  64  63 ...  97 100 102]
 ...
 [139 137 135 ... 141 144 137]
 [137 134 141 ... 169 194 175]
 [134 143 140 ... 174 174 180]]


In [166]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size =.2)
x_train[0].shape

(50, 50)

In [174]:
y_train = np.array(y_train)
y_test = np.array(y_test)
type(x_test)

numpy.ndarray

In [179]:
model = tf.keras.models.Sequential(
    [
        (tf.keras.layers.Flatten(input_shape = (50,50))),
         (tf.keras.layers.Dense(128,activation= 'relu')),
         (tf.keras.layers.Dense(128,activation= 'relu')),
         (tf.keras.layers.Dense(128,activation= 'relu')),
         (tf.keras.layers.Dense(128,activation= 'relu')),
         (tf.keras.layers.Dense(2,activation= tf.nn.softmax))
         
    ]
)

In [180]:
model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

In [182]:
model.fit(x_train,y_train,epochs =4)

Epoch 1/5
812/812 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5041 - loss: 0.6930
Epoch 2/5
812/812 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5010 - loss: 0.6931
Epoch 3/5
812/812 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5042 - loss: 0.6931
Epoch 4/5
812/812 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5024 - loss: 0.6931
Epoch 5/5
812/812 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.4928 - loss: 0.6932


In [183]:
val_loss = model.evaluate(x_test,y_test)


203/203 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5094 - loss: 0.6934
